#!/bin/bash
#
# .bash_profile
#
# John Van Note
# 2016-02-27
#
# .bash_profile for dotfiles
#


dotfiles=( \
    'aliases' \
    'aliases_git' \
    'bash_prompt' \
    'env_vars' \
    'global_git_config' \
    'muttrc' \
    'ruby' )

for dotfile in "${dotfiles[@]}"
do
    source ~/.$dotfile
done
